{% set version = "20251228" %}

package:
  name: pdfminer.six
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pdfminer.six/pdfminer_six-{{ version }}.tar.gz
  sha256: 5972b2babc5dd576a58634023b47e41ee827b505e36793cbfe37ac899000a1fb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
    - setuptools-git-versioning <2
  run:
    - python >={{ python_min }}
    - cryptography >=36.0.0
    - charset-normalizer >=2.0.0

test:
  imports:
    - pdfminer

  commands:
    - pip check
    - pdf2txt.py -h
    - dumppdf.py -h
    - pip check

  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pdfminer/pdfminer.six
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: PDF parser and analyzer
  description: |
    Pdfminer.six is a community maintained fork of the original PDFMiner. 
    It is a tool for extracting information from PDF documents. 
    It focuses on getting and analyzing text data. Pdfminer.six extracts 
    the text from a page directly from the sourcecode of the PDF. 
    It can also be used to get the exact location, font or color of the text.
  doc_url: https://pdfminersix.readthedocs.io
  dev_url: https://github.com/pdfminer/pdfminer.six

extra:
  recipe-maintainers:
    - pvanheus
    - estshorter
