{% set version = "20200124" %}

package:
  name: pdfminer.six
  version: {{ version }}

source:
  url: https://github.com/pdfminer/pdfminer.six/archive/{{ version}}.tar.gz
  sha256: f0f90e780725ee1fc87d45ad069798f04f846e9edd11dc8699de6898b019ada4

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - six
    - pycryptodome
    - sortedcontainers
    - chardet

test:
  imports:
    - pdfminer

  commands:
    - pdf2txt.py -h
    # Can't test dumppdf.py b/c -h raises issues.
    # Can't test latin2ascii.py unless you feed it input.

about:
  home: https://github.com/pdfminer/pdfminer.six
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'PDF parser and analyzer'
  dev_url: https://github.com/pdfminer/pdfminer.six

extra:
  recipe-maintainers:
    - pmlandwehr
    - pvanheus
