travis:
  secure:
    BINSTAR_TOKEN: KIFXhOX3/pDRTy86p1Fy+stdYYPK+vobHlWeZn0jYJD7Kps1q7Ac11GmqCZNBxX6ndBKK8naMYbA07sv/8DUtsZ3E4SZlGpt+yAXcxWkSKbGXwzkC6bOW+ZRZt8KkaVbEn2R85lzWHXeUo5j7ckd5v3/CiMPOCUSLw5bX8TeHIXMtfh68bWeY9NUVvH2DzZFuJMWbhBTMQ2O47aVrHGA4OgNBpOHH0x0ysFsffebC89wzFwkLKgkNCpTtxUnxONNSCj2iLWfDp/6Tji0RGeg6gnU2XCg8A/VYavkiHandHM1LFrlzrfpBTDnrp/p0pZ8eOMfwOrmu1UhuYBS3VKBKEC+otAEiO42C87hGQzv8qHXfaEdhQELAK8rpGAC6Ba7qlTEpSDAbWzeTOThUsYqgd5PKE1BAY6IAxYu5EEkQy8KBMIjkbvjCIzVv4JKq2oZH5z+buP++LsIfwTjE7GqJq12AoV4LybI/06ma2hzH9DZYTgHHvgLJDK9qFAi/uXtz9l7Y81I0uNTvNJPM4sTdq1TxTezoQoEktbTwqu/e3a8eTRCvuBGMZ8n+5M10CJv/0PjnlpWKS2G+fRliWIOGGzihvtH58uLy1RDP4SXC8Y6vX2mWPPmq2AI2mqWrrG/v4QZtzLfk1T9vthlpTThWFlGI2WG/2sneq2cEIdd4Bs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
